title: Crag to Competition
logo: /assets/climbing_pfp.jpeg
description: This is my term project for Introduction to Data Science (DSA 210) course in Sabancı University, Turkey
theme: jekyll-theme-minimal
